using System.Text;

namespace RPC.CodeGenerator.Emitter;

internal static partial class RpcHubEmitter
{
    static void EmitHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Communication.Network.RUDP.Shared.Messages;");
        sb.AppendLine("using Communication.Shared.Messages;");
        sb.AppendLine("using Communication.Shared.Sessions;");
        sb.AppendLine("using MessageProtocol;");
        sb.AppendLine("using MessageProtocol.Serialize;");
        sb.AppendLine("using RPC.Client.Network;");
        sb.AppendLine("using RPC.Server.Netwrok;");
        sb.AppendLine("using RPC.Shared;");
        sb.AppendLine("using RPC.Shared.Network;");
        sb.AppendLine("using LiteNetLib;");
        sb.AppendLine();
    }
}
