using System.Linq;
using System.Text;
using DRPC.CodeGenerator.Metadata;

namespace DRPC.CodeGenerator.Emitter;

/// <summary>
/// partial 허브 하나에 들어갈 생성 코드를 렌더링한다.
/// 구성: 생성자(수신 등록) → 접속/리스닝 → 페이로드 헬퍼 → outgoing 스텁 → incoming 디스패치.
/// </summary>
internal static partial class RpcHubEmitter
{
    const string SessionFactoryType =
        "global::System.Func<global::DRPC.Shared.Network.HubBase, global::Communication.Shared.Sessions.ISession>";

    public static string Emit(TypeMetadata model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// DRPC.CodeGenerator 가 생성했습니다. 직접 수정하지 마세요.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        string indent = "";
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        EmitPartialClass(sb, model, indent);

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    static void EmitPartialClass(StringBuilder sb, TypeMetadata model, string indent)
    {
        string hub = model.Symbol.Name;

        sb.AppendLine($"{indent}public partial class {hub}");
        sb.AppendLine($"{indent}{{");

        string inner = indent + "    ";

        EmitConstructor(sb, model, inner);

        if (model.IsServerEndpoint)
        {
            EmitListenAsync(sb, hub, inner);
        }
        else
        {
            EmitConnectAsync(sb, hub, inner);
        }

        foreach (MethodMetadata method in model.ServerDeclarations.Methods.Concat(model.ClientDeclarations.Methods))
        {
            if (method.IsGeneric)
            {
                EmitGenericPayloadHelpers(sb, method, inner);
            }
            else
            {
                EmitPayloadHelpers(sb, method, inner);
            }
        }

        foreach (MethodMetadata method in model.Outgoing)
        {
            if (method.IsGeneric)
            {
                EmitGenericOutgoing(sb, method, inner);
            }
            else
            {
                EmitOutgoing(sb, method, inner);
            }
        }

        foreach (MethodMetadata method in model.Incoming)
        {
            if (method.IsGeneric)
            {
                EmitGenericIncoming(sb, method, inner);
            }
            else
            {
                EmitIncoming(sb, method, inner);
            }
        }

        sb.AppendLine($"{indent}}}");
    }

    static void EmitConstructor(StringBuilder sb, TypeMetadata model, string indent)
    {
        string hub = model.Symbol.Name;

        // 사용자가 생성자를 직접 선언하면 겹치지 않게 건너뛴다(그 생성자가 sessionFactory 를 받아야 한다).
        if (!model.Symbol.InstanceConstructors.All(static c => c.IsImplicitlyDeclared))
        {
            return;
        }

        sb.AppendLine($"{indent}public {hub}({SessionFactoryType} sessionFactory)");
        sb.AppendLine($"{indent}    : base(sessionFactory)");
        sb.AppendLine($"{indent}{{");
        foreach (MethodMetadata method in model.Incoming)
        {
            sb.AppendLine($"{indent}    MethodCallActions.Add({method.MethodId}, {method.MethodName}_Requested);");
            sb.AppendLine($"{indent}    MethodDeliveryModes[{method.MethodId}] = {method.ModeExpression};");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    static void EmitConnectAsync(StringBuilder sb, string hub, string indent)
    {
        string connectBody =
            $"channel => new {hub}(h => global::DRPC.Shared.Network.HubSessionFactory.CreateRudpSession(channel, h))";

        sb.AppendLine($"{indent}/// <summary>서버에 접속해 허브를 만든다. 생성된 허브만 이 정적 메서드를 쓴다.</summary>");
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<{hub}> ConnectAsync(string host, int port, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => ConnectAsync(host, port, (string?)null, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<{hub}> ConnectAsync(string host, int port, string? connectionKey, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => global::DRPC.Client.Network.RpcClient.ConnectAsync(host, port, connectionKey, {connectBody}, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>RpcEndpointOptions 로 전송 옵션(키·DTLS·타임아웃 등)을 일괄 지정해 접속한다.</summary>");
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<{hub}> ConnectAsync(string host, int port, global::DRPC.Shared.Network.RpcEndpointOptions options, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => global::DRPC.Client.Network.RpcClient.ConnectWithOptionsAsync(host, port, options, {connectBody}, cancellationToken);");
        sb.AppendLine();
    }

    static void EmitListenAsync(StringBuilder sb, string hub, string indent)
    {
        string listenFactory =
            $"channel => new {hub}(h => global::DRPC.Shared.Network.HubSessionFactory.CreateRudpSession(channel, h))";

        sb.AppendLine($"{indent}/// <summary>port 를 받아 peer 마다 허브를 만든다. 반환 핸들을 Dispose 하면 리스너와 peer 가 정리된다.</summary>");
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<global::DRPC.Shared.Network.RpcListenHandle> ListenAsync(int port, global::System.Func<{hub}, global::System.Threading.Tasks.Task> onConnected, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => ListenAsync(port, (string?)null, onConnected, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<global::DRPC.Shared.Network.RpcListenHandle> ListenAsync(int port, string? connectionKey, global::System.Func<{hub}, global::System.Threading.Tasks.Task> onConnected, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => global::DRPC.Server.Network.RpcHost.ListenAsync(port, connectionKey, {listenFactory}, onConnected, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>RpcEndpointOptions 로 전송 옵션(키·DTLS·타임아웃 등)을 일괄 지정해 리스닝한다.</summary>");
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<global::DRPC.Shared.Network.RpcListenHandle> ListenAsync(int port, global::DRPC.Shared.Network.RpcEndpointOptions options, global::System.Func<{hub}, global::System.Threading.Tasks.Task> onConnected, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => global::DRPC.Server.Network.RpcHost.ListenWithOptionsAsync(port, options, {listenFactory}, onConnected, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<global::DRPC.Shared.Network.RpcListenHandle> ListenAsync(int port, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => global::DRPC.Server.Network.RpcHost.ListenAsync(port, null, {listenFactory}, null, cancellationToken);");
        sb.AppendLine();
    }

    static void EmitOutgoing(StringBuilder sb, MethodMetadata method, string indent)
    {
        string args = string.Join(", ", method.Parameters.Select(static p => p.Name));
        string asyncReturn = method.IsVoidReturn || method.OneWay
            ? "global::System.Threading.Tasks.Task"
            : $"global::System.Threading.Tasks.Task<{method.ReturnTypeDisplay}>";

        // 왕복 호출은 호출자 취소를 받는다(맨 끝 선택 매개변수). one-way 송신은 대기가 없어 제외한다.
        string ctParam = method.OneWay ? "" : CancellationTokenParam(method);

        sb.AppendLine($"{indent}public async {asyncReturn} {method.MethodName}Async({method.ParameterDeclarationList()}{ctParam})");
        sb.AppendLine($"{indent}{{");
        EmitPayloadWrite(sb, indent + "    ", method, args, "__payload");

        if (method.OneWay)
        {
            sb.AppendLine($"{indent}    await SendRPC({method.MethodId}, __payload, {method.ModeExpression}).ConfigureAwait(false);");
        }
        else if (method.IsVoidReturn)
        {
            sb.AppendLine($"{indent}    await RequestRPC({method.MethodId}, __payload, {method.ModeExpression}{TimeoutArg(method)}, cancellationToken).ConfigureAwait(false);");
        }
        else
        {
            sb.AppendLine($"{indent}    byte[] __response = await RequestRPC({method.MethodId}, __payload, {method.ModeExpression}{TimeoutArg(method)}, cancellationToken).ConfigureAwait(false);");
            sb.AppendLine($"{indent}    return {ReadReturn(method)}(__response);");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    /// <summary>왕복 스텁 맨 끄트에 붙는 선택 취소 토큰 매개변수(무득수 메서드면 앞 쉼표 없이).</summary>
    static string CancellationTokenParam(MethodMetadata method)
        => (method.Parameters.Length == 0 ? "" : ", ")
            + "global::System.Threading.CancellationToken cancellationToken = default";

    /// <summary>
    /// 호출별 타임아웃 인수(쉼표 포함). TimeoutMs 미지정(-1)이면 빈 문자열 — 기존 생성 텍스트와 바이트 단위 동일.
    /// 양수면 <c>TimeSpan.FromMilliseconds(N)</c> 을 전송 방식 뒤에 끼워 넣는다(일반·제네릭 이미터 공용).
    /// </summary>
    internal static string TimeoutArg(MethodMetadata method)
        => method.TimeoutMs > 0
            ? $", global::System.TimeSpan.FromMilliseconds({method.TimeoutMs})"
            : "";

    static void EmitIncoming(StringBuilder sb, MethodMetadata method, string indent)
    {
        sb.AppendLine($"{indent}private async global::System.Threading.Tasks.Task<byte[]> {method.MethodName}_Requested(byte[] __parameterData)");
        sb.AppendLine($"{indent}{{");
        string args = "";
        if (method.Parameters.Length > 0)
        {
            for (int i = 0; i < method.Parameters.Length; i++)
            {
                sb.AppendLine($"{indent}    {method.Parameters[i].Type.ToDisplayString(RpcPayload.Qualified)} {method.Parameters[i].Name} = default!;");
            }

            string outs = string.Join(", ", method.Parameters.Select(p => $"out {p.Name}"));
            sb.AppendLine($"{indent}    {ReadParams(method)}(__parameterData, {outs});");
            args = string.Join(", ", method.Parameters.Select(static p => p.Name));
        }

        EmitValidationGate(sb, method, args, indent + "    ");

        if (method.IsVoidReturn)
        {
            sb.AppendLine($"{indent}    await {method.MethodName}_Implementation({args}).ConfigureAwait(false);");
            sb.AppendLine($"{indent}    return global::System.Array.Empty<byte>();");
        }
        else
        {
            sb.AppendLine($"{indent}    {method.ReturnTypeDisplay} __result = await {method.MethodName}_Implementation({args}).ConfigureAwait(false);");
            sb.AppendLine($"{indent}    return {WriteReturn(method)}(__result);");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent}private partial {method.ImplementationSignature};");
        EmitValidateDeclaration(sb, method, indent);
    }

    /// <summary>Validation=true 메서드의 _Validate 게이트 — false 반환 시 ValidationFailed 예외로 구현 호출을 끊는다. 제네릭은 typeArgs 로 닫힌 타입 인수를 넘긴다.</summary>
    internal static void EmitValidationGate(StringBuilder sb, MethodMetadata method, string args, string indent, string typeArgs = "")
    {
        if (!method.Validation)
        {
            return;
        }

        sb.AppendLine($"{indent}if (!await {method.MethodName}_Validate{typeArgs}({args}).ConfigureAwait(false))");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    throw new global::DRPC.Shared.RpcValidationFailedException(\"{method.MethodName}\");");
        sb.AppendLine($"{indent}}}");
    }

    /// <summary>Validation=true 일 때 _Validate partial 선언을 추가한다(미구현 시 컴파일 에러 — fail-closed).</summary>
    internal static void EmitValidateDeclaration(StringBuilder sb, MethodMetadata method, string indent)
    {
        if (!method.Validation)
        {
            return;
        }

        sb.AppendLine($"{indent}private partial {method.ValidateSignature};");
        sb.AppendLine();
    }

    // ── 페이로드 헬퍼 이름 ───────────────────────────────────────────────

    static string WriteParams(MethodMetadata m) => $"__WriteParams_{m.DeclarationName}_{m.MethodName}";

    static string ReadParams(MethodMetadata m) => $"__ReadParams_{m.DeclarationName}_{m.MethodName}";

    static string WriteReturn(MethodMetadata m) => $"__WriteReturn_{m.DeclarationName}_{m.MethodName}";

    static string ReadReturn(MethodMetadata m) => $"__ReadReturn_{m.DeclarationName}_{m.MethodName}";
}
