using System.Text;
using RPC.CodeGenerator.Meta;

namespace RPC.CodeGenerator.Generate;

/// <summary>
/// <c>{MethodName}_Parameter</c> NonIdMessage 페이로드 선언 — MessageProtocol.CodeGenerator 가 직렬화 partial을 생성합니다.
/// </summary>
internal static class RpcParameterPayloadFragments
{
    public static void AppendNestedParameterPayload(StringBuilder sb, RpcHubKind hubKind, RpcMethodEmitMeta m,
        string indent)
    {
        if (m.Parameters.Length == 0)
            return;

        var i1 = indent;
        var i2 = indent + "\t";
        var i3 = indent + "\t\t";

        sb.Append(i1).AppendLine("[global::MessageProtocol.NonIdMessage]");
        if (hubKind == RpcHubKind.ClientSideServerHub)
            sb.Append(i1).Append("public partial class ").Append(m.Name).AppendLine("_Parameter");
        else
            sb.Append(i1).Append("partial struct ").Append(m.Name).AppendLine("_Parameter");

        sb.Append(i1).AppendLine("{");
        foreach (var p in m.Parameters)
        {
            sb.Append(i2).Append("public ").Append(RpcSourceEmitter.FormatRpcParameterTypeForPayload(p.Kind, p.TypeDisplay))
                .Append(' ').Append(p.Name).AppendLine(";");
        }

        sb.AppendLine();
        if (hubKind == RpcHubKind.ClientSideServerHub)
        {
            sb.Append(i2).Append("public ").Append(m.Name).AppendLine("_Parameter() { }");
            sb.Append(i2).Append("public ").Append(m.Name).Append("_Parameter(");
            for (var j = 0; j < m.Parameters.Length; j++)
            {
                if (j > 0) sb.Append(", ");
                sb.Append(RpcSourceEmitter.FormatRpcParameterTypeForPayload(m.Parameters[j].Kind, m.Parameters[j].TypeDisplay))
                    .Append(' ').Append(m.Parameters[j].Name);
            }

            sb.AppendLine(")");
            sb.Append(i2).AppendLine("{");
            foreach (var p in m.Parameters)
                sb.Append(i3).Append("this.").Append(p.Name).Append(" = ").Append(p.Name).AppendLine(";");
            sb.Append(i2).AppendLine("}");
        }
        else
        {
            sb.Append(i2).Append("public ").Append(m.Name).Append("_Parameter(");
            for (var j = 0; j < m.Parameters.Length; j++)
            {
                if (j > 0) sb.Append(", ");
                sb.Append(RpcSourceEmitter.FormatRpcParameterTypeForPayload(m.Parameters[j].Kind, m.Parameters[j].TypeDisplay))
                    .Append(' ').Append(m.Parameters[j].Name);
            }

            sb.AppendLine(")");
            sb.Append(i2).AppendLine("{");
            foreach (var p in m.Parameters)
                sb.Append(i3).Append("this.").Append(p.Name).Append(" = ").Append(p.Name).AppendLine(";");
            sb.Append(i2).AppendLine("}");
        }

        sb.Append(i1).AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// MessageSerializeCodeEmitter 용 문법 트리 (실제 허브 파일과 동일한 중첩 형태).
    /// </summary>
    public static string BuildProbeSyntaxTree(string? namespaceName, string hubClassName, RpcHubKind kind,
        System.Collections.Immutable.ImmutableArray<RpcMethodEmitMeta> methodsWithParams)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using MessageProtocol;");
        sb.AppendLine();

        if (namespaceName is { Length: > 0 })
        {
            sb.Append("namespace ").Append(namespaceName).AppendLine();
            sb.AppendLine("{");
            sb.Append("\tpublic partial class ").Append(hubClassName).AppendLine();
            sb.Append("\t{");
            foreach (var m in methodsWithParams)
            {
                sb.AppendLine();
                AppendNestedParameterPayload(sb, kind, m, indent: "\t\t");
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");
        }
        else
        {
            sb.Append("public partial class ").Append(hubClassName).AppendLine();
            sb.AppendLine("{");
            foreach (var m in methodsWithParams)
            {
                sb.AppendLine();
                AppendNestedParameterPayload(sb, kind, m, indent: "\t");
            }

            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
