using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using RPC.CodeGenerator.Meta;

namespace RPC.CodeGenerator.Generate;

internal static class RpcSourceEmitter
{
    public static string Emit(RpcHubEmitMeta model)
    {
        var sb = new StringBuilder(16_384);
        sb.Append(@"// <auto-generated />
#nullable enable

using Communication.Network.RUDP.Shared.Messages;
using Communication.Shared.Messages;
using Communication.Shared.Sessions;
using MessageProtocol;
using MessageProtocol.Serialize;
using RPC.Shared;
using RPC.Shared.Interface;
using RPC.Shared.Network;

");

        if (model.Kind == RpcHubKind.ClientSideServerHub)
            sb.AppendLine("using RPC.Client.Network;");
        else
            sb.AppendLine("using RPC.Server.Netwrok;");
        sb.AppendLine();

        if (model.Namespace is { } ns)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("public partial class ").Append(model.ClassName).AppendLine();
        sb.AppendLine("{");

        if (model.Kind == RpcHubKind.ClientSideServerHub)
            EmitClientSideServerHub(sb, model);
        else
            EmitServerSideClientHub(sb, model);

        sb.AppendLine("}");

        sb.AppendLine();
        sb.AppendLine("#nullable restore");
        return sb.ToString();
    }

    private static void EmitClientSideServerHub(StringBuilder sb, RpcHubEmitMeta model)
    {
        EmitConstructor(sb, model, model.ClientProcedures);
        sb.AppendLine();
        EmitConnectAsync(sb, model.ClassName);
        sb.AppendLine();

        foreach (var m in model.ClientProcedures)
        {
            EmitIncomingHandler(sb, model.ClassName, m, isServerExecution: false);
            sb.AppendLine();
            EmitPartialDeclaration(sb, m, isServerExecution: false);
            sb.AppendLine();
        }

        foreach (var m in model.ServerProcedures)
        {
            EmitOutgoingCaller(sb, m);
            sb.AppendLine();
        }

        EmitNonIdMessagePayloadTypes(sb, model);
        EmitDefaultMessageConverter(sb);
    }

    private static void EmitServerSideClientHub(StringBuilder sb, RpcHubEmitMeta model)
    {
        EmitConstructor(sb, model, model.ServerProcedures);
        sb.AppendLine();
        EmitListenAsync(sb, model.ClassName);
        sb.AppendLine();

        foreach (var m in model.ServerProcedures)
        {
            EmitIncomingHandler(sb, model.ClassName, m, isServerExecution: true);
            sb.AppendLine();
            EmitPartialDeclaration(sb, m, isServerExecution: true);
            sb.AppendLine();
        }

        foreach (var m in model.ClientProcedures)
        {
            EmitOutgoingCaller(sb, m);
            sb.AppendLine();
        }

        EmitNonIdMessagePayloadTypes(sb, model);
        EmitDefaultMessageConverter(sb);
    }

    private static void EmitNonIdMessagePayloadTypes(StringBuilder sb, RpcHubEmitMeta model)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var m in model.ClientProcedures)
        {
            if (m.Parameters.Length == 0 || !seen.Add(m.Name))
                continue;
            RpcParameterPayloadFragments.AppendNestedParameterPayload(sb, model.Kind, m, "\t");
        }

        foreach (var m in model.ServerProcedures)
        {
            if (m.Parameters.Length == 0 || !seen.Add(m.Name))
                continue;
            RpcParameterPayloadFragments.AppendNestedParameterPayload(sb, model.Kind, m, "\t");
        }
    }

    private static void EmitConstructor(StringBuilder sb, RpcHubEmitMeta model, ImmutableArray<RpcMethodEmitMeta> handlerMethods)
    {
        sb.Append("\tpublic ").Append(model.ClassName).AppendLine("(global::System.Func<global::RPC.Shared.Network.HubBase, global::Communication.Shared.Sessions.ISession> sessionFactory)");
        sb.AppendLine("\t\t: base(sessionFactory)");
        sb.AppendLine("\t{");
        foreach (var m in handlerMethods)
        {
            sb.Append("\t\tMethodCallActions.Add(").Append(m.MethodId).Append(", ").Append(m.Name)
                .AppendLine("_Requested);");
        }

        sb.AppendLine("\t}");
    }

    private static void EmitConnectAsync(StringBuilder sb, string className)
    {
        sb.Append($@"	public static async global::System.Threading.Tasks.Task<{className}> ConnectAsync(string host, int port, global::System.Threading.CancellationToken cancellationToken)
	{{
		return await ConnectAsync(host, port, """", cancellationToken);
	}}

	public static async global::System.Threading.Tasks.Task<{className}> ConnectAsync(string host, int port, string connectionKey, global::System.Threading.CancellationToken cancellationToken)
	{{
		{className}? connectedHub = null;
		Connector connector = new(host, port, connectionKey);

		bool isConnected = await connector.ConnectAsync((peer, netManager, listener) =>
		{{
			connectedHub = new {className}(hub =>
				new ServerSession(
					peer,
					netManager,
					session => new RUDPMessageReceiver(
						new DefaultMessageConverter(),
						peer,
						netManager,
						listener,
						new RPCMessageHandler(session, hub)),
					_ => new RUDPMessageSender(
						new DefaultMessageConverter(),
						peer)));

			_ = global::System.Threading.Tasks.Task.Run(async () =>
			{{
				while (!cancellationToken.IsCancellationRequested)
				{{
					netManager.PollEvents();
					await global::System.Threading.Tasks.Task.Delay(10);
				}}
			}}, cancellationToken);

			return global::System.Threading.Tasks.Task.CompletedTask;
		}});

		if (isConnected == false || connectedHub == null)
			throw new global::System.InvalidOperationException(""Failed to connect to server."");

		return connectedHub;
	}}
");
    }

    private static void EmitListenAsync(StringBuilder sb, string className)
    {
        sb.Append($@"	public static global::System.Threading.Tasks.Task ListenAsync(int port, global::System.Func<{className}, global::System.Threading.Tasks.Task> onConnected, global::System.Threading.CancellationToken cancellationToken)
	{{
		return ListenAsync(port, """", onConnected, cancellationToken);
	}}

	public static async global::System.Threading.Tasks.Task ListenAsync(int port, string connectionKey, global::System.Func<{className}, global::System.Threading.Tasks.Task> onConnected, global::System.Threading.CancellationToken cancellationToken)
	{{
		Listener listener = new(global::System.Net.IPAddress.Any, port, connectionKey);

		await listener.ListenAsync(async (peer, netManager, eventListener) =>
		{{
			{className} hub = new(_ =>
				new ClientSession(
					peer,
					netManager,
					session => new RUDPMessageReceiver(
						new DefaultMessageConverter(),
						peer,
						netManager,
						eventListener,
						new RPCMessageHandler(session, _)),
					__ => new RUDPMessageSender(
						new DefaultMessageConverter(),
						peer)));

			await onConnected(hub);
		}}, cancellationToken);
	}}
");
    }

    private static void EmitIncomingHandler(StringBuilder sb, string hubClassName, RpcMethodEmitMeta m,
        bool isServerExecution)
    {
        _ = hubClassName;
        _ = isServerExecution;
        sb.Append("\tprivate byte[] ").Append(m.Name).AppendLine("_Requested(byte[] parameterData)");
        sb.AppendLine("\t{");

        if (m.Parameters.Length > 0)
        {
            sb.Append("\t\t").Append(m.Name).Append("_Parameter parameter = global::MessageProtocol.Serialize.MessageSerializer.Deserialize<")
                .Append(m.Name).Append("_Parameter>(parameterData);").AppendLine();
        }

        var implPrefix = m.Parameters.Length > 0 ? "parameter." : "";
        if (m.ReturnKind == RpcEmitReturnKind.Void)
        {
            sb.Append("\t\t");
            AppendImplementationCall(sb, m, implPrefix);
            sb.AppendLine(";");
            sb.AppendLine("\t\treturn global::System.Array.Empty<byte>();");
        }
        else
        {
            sb.Append("\t\t");
            AppendReturnTypeKeyword(sb, m.ReturnKind);
            sb.Append(" result = ");
            AppendImplementationCall(sb, m, implPrefix);
            sb.AppendLine(";");
            sb.AppendLine("\t\treturn global::System.BitConverter.GetBytes(result);");
        }

        sb.AppendLine("\t}");
    }

    private static void AppendImplementationCall(StringBuilder sb, RpcMethodEmitMeta m, string memberPrefix)
    {
        sb.Append(m.Name).Append("_Implementation(");
        for (var i = 0; i < m.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(memberPrefix).Append(m.Parameters[i].Name);
        }

        sb.Append(')');
    }

    private static void EmitPartialDeclaration(StringBuilder sb, RpcMethodEmitMeta m, bool isServerExecution)
    {
        _ = isServerExecution;
        sb.Append("\tprivate partial ");
        AppendReturnTypeKeyword(sb, m.ReturnKind);
        sb.Append(' ').Append(m.Name).Append("_Implementation(");
        for (var i = 0; i < m.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(FormatRpcParameterTypeForPayload(m.Parameters[i].Kind, m.Parameters[i].TypeDisplay)).Append(' ')
                .Append(m.Parameters[i].Name);
        }

        sb.AppendLine(");");
    }

    private static void AppendReturnTypeKeyword(StringBuilder sb, RpcEmitReturnKind kind)
    {
        sb.Append(kind switch
        {
            RpcEmitReturnKind.Void => "void",
            RpcEmitReturnKind.Float => "float",
            RpcEmitReturnKind.Double => "double",
            RpcEmitReturnKind.Int => "int",
            RpcEmitReturnKind.Long => "long",
            RpcEmitReturnKind.Short => "short",
            RpcEmitReturnKind.Byte => "byte",
            RpcEmitReturnKind.Bool => "bool",
            _ => "void"
        });
    }

    /// <summary>부분 메서드 정의/구현 서명이 사용자 코드(float 등)와 동일하게 맞도록 원시 타입은 키워드를 씁니다.</summary>
    internal static string FormatRpcParameterTypeForPayload(RpcEmitReturnKind kind, string roslynTypeDisplay)
    {
        return kind switch
        {
            RpcEmitReturnKind.Float => "float",
            RpcEmitReturnKind.Double => "double",
            RpcEmitReturnKind.Int => "int",
            RpcEmitReturnKind.Long => "long",
            RpcEmitReturnKind.Short => "short",
            RpcEmitReturnKind.Byte => "byte",
            RpcEmitReturnKind.Bool => "bool",
            _ => DisplayTypeAsField(roslynTypeDisplay)
        };
    }

    /// <summary>global:: 접두사는 필드 선언에서 제거합니다.</summary>
    private static string DisplayTypeAsField(string fullyQualified)
    {
        const string prefix = "global::";
        return fullyQualified.StartsWith(prefix, StringComparison.Ordinal)
            ? fullyQualified.Substring(prefix.Length)
            : fullyQualified;
    }

    private static void EmitOutgoingCaller(StringBuilder sb, RpcMethodEmitMeta m)
    {
        sb.Append("\tpublic ");
        AppendReturnTypeKeyword(sb, m.ReturnKind);
        sb.Append(' ').Append(m.Name).Append('(');
        for (var i = 0; i < m.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(FormatRpcParameterTypeForPayload(m.Parameters[i].Kind, m.Parameters[i].TypeDisplay)).Append(' ')
                .Append(m.Parameters[i].Name);
        }

        sb.AppendLine(")");
        sb.AppendLine("\t{");
        EmitOutgoingRpcParameterSerialization(sb, m);

        if (m.Parameters.Length == 0)
            sb.Append("\t\tglobal::System.Threading.Tasks.Task<byte[]> RPCTask = RequestRPC(").Append(m.MethodId)
                .Append(", global::System.Array.Empty<byte>(), ").Append(m.ReliableTypeExpression).AppendLine(");");
        else
            sb.Append("\t\tglobal::System.Threading.Tasks.Task<byte[]> RPCTask = RequestRPC(").Append(m.MethodId)
                .Append(", parameterData, ").Append(m.ReliableTypeExpression).AppendLine(");");

        sb.AppendLine("\t\tRPCTask.Wait();");

        if (m.ReturnKind == RpcEmitReturnKind.Void)
        {
            sb.AppendLine("\t}");
            sb.AppendLine();
            EmitAsyncCaller(sb, m);
            return;
        }

        sb.Append("\t\treturn ").Append(ReadResultExpression(m.ReturnKind)).AppendLine(";");
        sb.AppendLine("\t}");
        sb.AppendLine();
        EmitAsyncCaller(sb, m);
    }

    private static void EmitAsyncCaller(StringBuilder sb, RpcMethodEmitMeta m)
    {
        sb.Append("\tpublic async global::System.Threading.Tasks.");
        if (m.ReturnKind == RpcEmitReturnKind.Void)
            sb.Append("Task ");
        else
            sb.Append("Task<").Append(GetReturnTypeDisplay(m.ReturnKind)).Append("> ");

        sb.Append(m.Name).Append("Async(");
        for (var i = 0; i < m.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(FormatRpcParameterTypeForPayload(m.Parameters[i].Kind, m.Parameters[i].TypeDisplay)).Append(' ')
                .Append(m.Parameters[i].Name);
        }

        sb.AppendLine(")");
        sb.AppendLine("\t{");
        EmitOutgoingRpcParameterSerialization(sb, m);

        if (m.Parameters.Length == 0)
            sb.Append("\t\tglobal::System.Threading.Tasks.Task<byte[]> RPCTask = RequestRPC(").Append(m.MethodId)
                .Append(", global::System.Array.Empty<byte>(), ").Append(m.ReliableTypeExpression).AppendLine(");");
        else
            sb.Append("\t\tglobal::System.Threading.Tasks.Task<byte[]> RPCTask = RequestRPC(").Append(m.MethodId)
                .Append(", parameterData, ").Append(m.ReliableTypeExpression).AppendLine(");");

        sb.AppendLine("\t\tawait RPCTask;");

        if (m.ReturnKind == RpcEmitReturnKind.Void)
        {
            sb.AppendLine("\t}");
            return;
        }

        sb.Append("\t\treturn ").Append(ReadResultExpression(m.ReturnKind)).AppendLine(";");
        sb.AppendLine("\t}");
    }

    private static void EmitOutgoingRpcParameterSerialization(StringBuilder sb, RpcMethodEmitMeta m)
    {
        if (m.Parameters.Length == 0)
            return;

        sb.Append("\t\t").Append(m.Name).Append("_Parameter parameter = new(");
        for (var i = 0; i < m.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(m.Parameters[i].Name);
        }

        sb.AppendLine(");");
        sb.AppendLine(
            "\t\tbyte[] parameterData = global::MessageProtocol.Serialize.MessageSerializer.Serialize(parameter);");
    }

    private static string GetReturnTypeDisplay(RpcEmitReturnKind kind) => kind switch
    {
        RpcEmitReturnKind.Float => "float",
        RpcEmitReturnKind.Double => "double",
        RpcEmitReturnKind.Int => "int",
        RpcEmitReturnKind.Long => "long",
        RpcEmitReturnKind.Short => "short",
        RpcEmitReturnKind.Byte => "byte",
        RpcEmitReturnKind.Bool => "bool",
        _ => "object"
    };

    private static string ReadResultExpression(RpcEmitReturnKind kind) => kind switch
    {
        RpcEmitReturnKind.Float => "global::System.BitConverter.ToSingle(RPCTask.Result, 0)",
        RpcEmitReturnKind.Double => "global::System.BitConverter.ToDouble(RPCTask.Result, 0)",
        RpcEmitReturnKind.Int => "global::System.BitConverter.ToInt32(RPCTask.Result, 0)",
        RpcEmitReturnKind.Long => "global::System.BitConverter.ToInt64(RPCTask.Result, 0)",
        RpcEmitReturnKind.Short => "global::System.BitConverter.ToInt16(RPCTask.Result, 0)",
        RpcEmitReturnKind.Byte => "RPCTask.Result[0]",
        RpcEmitReturnKind.Bool => "global::System.BitConverter.ToBoolean(RPCTask.Result, 0)",
        _ => "RPCTask.Result"
    };

    private static void EmitDefaultMessageConverter(StringBuilder sb)
    {
        sb.Append(@"	private sealed class DefaultMessageConverter : IMessageConverter
	{
		public byte[] Serialize(object message)
		{
			return MessageSerializer.Serialize(message);
		}

		public object Deserialize(global::System.ReadOnlySpan<byte> messageData)
		{
			return MessageSerializer.Deserialize(messageData.ToArray());
		}
	}
");
    }
}
