using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using RPC.CodeGenerator.Metadata;

namespace RPC.CodeGenerator;

internal static class RpcHubEmitter
{
    public static string Emit(RpcHubEmitModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Communication.Network.RUDP.Shared.Messages;");
        sb.AppendLine("using Communication.Shared.Messages;");
        sb.AppendLine("using Communication.Shared.Sessions;");
        sb.AppendLine("using MessageProtocol;");
        sb.AppendLine("using MessageProtocol.Serialize;");
        sb.AppendLine("using RPC.Client.Network;");
        sb.AppendLine("using RPC.Server.Netwrok;");
        sb.AppendLine("using RPC.Shared;");
        sb.AppendLine("using RPC.Shared.Network;");
        sb.AppendLine("using LiteNetLib;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        string indent = string.IsNullOrEmpty(model.Namespace) ? "" : "    ";
        EmitPartialClass(sb, model, indent);

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    static void EmitPartialClass(StringBuilder sb, RpcHubEmitModel model, string indent)
    {
        string hub = model.HubTypeName;

        sb.AppendLine($"{indent}public partial class {hub}");
        sb.AppendLine($"{indent}{{");

        EmitConstructors(sb, model, indent + "    ");

        if (model.IsServerEndpoint)
        {
            EmitListenAsync(sb, hub, indent + "    ");
        }
        else
        {
            EmitConnectAsync(sb, hub, indent + "    ");
        }

        foreach (var proc in model.Outgoing)
        {
            EmitOutgoingProcedure(sb, proc, indent + "    ");
        }

        foreach (var proc in model.Incoming)
        {
            EmitIncomingProcedure(sb, proc, indent + "    ");
        }

        EmitDefaultMessageConverter(sb, indent + "    ");

        if (model.NeedsStringHelpers)
        {
            EmitStringHelpers(sb, indent + "    ");
        }

        sb.AppendLine($"{indent}}}");
    }

    static void EmitConstructors(StringBuilder sb, RpcHubEmitModel model, string indent)
    {
        string hub = model.HubTypeName;
        sb.AppendLine($"{indent}public {hub}(global::System.Func<HubBase, ISession> sessionFactory)");
        sb.AppendLine($"{indent}    : base(sessionFactory)");
        sb.AppendLine($"{indent}{{");
        foreach (var proc in model.Incoming)
        {
            sb.AppendLine($"{indent}    MethodCallActions.Add({proc.MethodId}, {proc.MethodName}_Requested);");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    static void EmitListenAsync(StringBuilder sb, string hubTypeName, string indent)
    {
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task ListenAsync(int port, global::System.Func<{hubTypeName}, global::System.Threading.Tasks.Task> onConnected, global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    return ListenAsync(port, \"\", onConnected, cancellationToken);");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent}public static async global::System.Threading.Tasks.Task ListenAsync(int port, string connectionKey, global::System.Func<{hubTypeName}, global::System.Threading.Tasks.Task> onConnected, global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    Listener listener = new(global::System.Net.IPAddress.Any, port, connectionKey);");
        sb.AppendLine($"{indent}    int sessionId = 0;");
        sb.AppendLine($"{indent}    await listener.ListenAsync(async (peer, netManager, eventListener) =>");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        {hubTypeName} hub = new(_ =>");
        sb.AppendLine($"{indent}            new ClientSession(");
        sb.AppendLine($"{indent}                global::System.Threading.Interlocked.Increment(ref sessionId),");
        sb.AppendLine($"{indent}                peer,");
        sb.AppendLine($"{indent}                netManager,");
        sb.AppendLine($"{indent}                session => new RUDPMessageReceiver(");
        sb.AppendLine($"{indent}                    new DefaultMessageConverter(),");
        sb.AppendLine($"{indent}                    peer,");
        sb.AppendLine($"{indent}                    netManager,");
        sb.AppendLine($"{indent}                    eventListener,");
        sb.AppendLine($"{indent}                    new RPCMessageHandler(session, _)),");
        sb.AppendLine($"{indent}                __ => new RUDPMessageSender(");
        sb.AppendLine($"{indent}                    new DefaultMessageConverter(),");
        sb.AppendLine($"{indent}                    peer)));");
        sb.AppendLine();
        sb.AppendLine($"{indent}        await onConnected(hub);");
        sb.AppendLine();
        sb.AppendLine($"{indent}        _ = global::System.Threading.Tasks.Task.Run(async () =>");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            while (!cancellationToken.IsCancellationRequested)");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                netManager.PollEvents();");
        sb.AppendLine($"{indent}                await global::System.Threading.Tasks.Task.Delay(10);");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}        }}, cancellationToken);");
        sb.AppendLine($"{indent}    }}, cancellationToken);");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    static void EmitConnectAsync(StringBuilder sb, string hubTypeName, string indent)
    {
        sb.AppendLine($"{indent}public static async global::System.Threading.Tasks.Task<{hubTypeName}> ConnectAsync(string host, int port, global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    return await ConnectAsync(host, port, \"\", cancellationToken);");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent}public static async global::System.Threading.Tasks.Task<{hubTypeName}> ConnectAsync(string host, int port, string connectionKey, global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    {hubTypeName}? connectedHub = null;");
        sb.AppendLine($"{indent}    Connector connector = new(host, port, connectionKey);");
        sb.AppendLine();
        sb.AppendLine($"{indent}    bool isConnected = await connector.ConnectAsync((peer, netManager, listener) =>");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        connectedHub = new {hubTypeName}(hub =>");
        sb.AppendLine($"{indent}            new ServerSession(");
        sb.AppendLine($"{indent}                peer,");
        sb.AppendLine($"{indent}                netManager,");
        sb.AppendLine($"{indent}                session => new RUDPMessageReceiver(");
        sb.AppendLine($"{indent}                    new DefaultMessageConverter(),");
        sb.AppendLine($"{indent}                    peer,");
        sb.AppendLine($"{indent}                    netManager,");
        sb.AppendLine($"{indent}                    listener,");
        sb.AppendLine($"{indent}                    new RPCMessageHandler(session, hub)),");
        sb.AppendLine($"{indent}                _ => new RUDPMessageSender(");
        sb.AppendLine($"{indent}                    new DefaultMessageConverter(),");
        sb.AppendLine($"{indent}                    peer)));");
        sb.AppendLine();
        sb.AppendLine($"{indent}        _ = global::System.Threading.Tasks.Task.Run(async () =>");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            while (!cancellationToken.IsCancellationRequested)");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                netManager.PollEvents();");
        sb.AppendLine($"{indent}                await global::System.Threading.Tasks.Task.Delay(10);");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}        }}, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine($"{indent}        return global::System.Threading.Tasks.Task.CompletedTask;");
        sb.AppendLine($"{indent}    }});");
        sb.AppendLine();
        sb.AppendLine($"{indent}    if (isConnected == false || connectedHub == null)");
        sb.AppendLine($"{indent}        throw new global::System.InvalidOperationException(\"Failed to connect to server.\");");
        sb.AppendLine();
        sb.AppendLine($"{indent}    return connectedHub;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    static void EmitOutgoingProcedure(StringBuilder sb, MethodMetadata proc, string indent)
    {
        string syncReturn = proc.ReturnType.SpecialType == SpecialType.System_Void
            ? "void"
            : proc.ReturnType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

        string asyncReturn = proc.ReturnType.SpecialType == SpecialType.System_Void
            ? "global::System.Threading.Tasks.Task"
            : $"global::System.Threading.Tasks.Task<{proc.ReturnType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}>";

        var paramList = string.Join(", ", proc.Parameters.Select(p =>
            $"{p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)} {p.Name}"));

        // Sync
        if (proc.ReturnType.SpecialType == SpecialType.System_Void)
        {
            sb.AppendLine($"{indent}public void {proc.MethodName}({paramList})");
            sb.AppendLine($"{indent}{{");
            if (proc.Parameters.Length == 0)
            {
                sb.AppendLine($"{indent}    byte[] parameterData = global::System.Array.Empty<byte>();");
            }
            else
            {
                RpcBinaryCodec.EmitSerializeParameters(sb, indent + "    ", proc.Parameters);
            }

            sb.AppendLine($"{indent}    global::System.Threading.Tasks.Task<byte[]> rpcTask = RequestRPC({proc.MethodId}, parameterData, {proc.ReliableTypeExpression});");
            sb.AppendLine($"{indent}    rpcTask.GetAwaiter().GetResult();");
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            sb.AppendLine($"{indent}public {syncReturn} {proc.MethodName}({paramList})");
            sb.AppendLine($"{indent}{{");
            if (proc.Parameters.Length == 0)
            {
                sb.AppendLine($"{indent}    byte[] parameterData = global::System.Array.Empty<byte>();");
            }
            else
            {
                RpcBinaryCodec.EmitSerializeParameters(sb, indent + "    ", proc.Parameters);
            }

            sb.AppendLine($"{indent}    global::System.Threading.Tasks.Task<byte[]> rpcTask = RequestRPC({proc.MethodId}, parameterData, {proc.ReliableTypeExpression});");
            sb.AppendLine($"{indent}    byte[] resultBytes = rpcTask.GetAwaiter().GetResult();");
            sb.AppendLine($"{indent}    return {RpcMarshal.EmitDecodeReturnExpression(proc.ReturnType, "resultBytes")};");
            sb.AppendLine($"{indent}}}");
        }

        sb.AppendLine();

        // Async
        if (proc.ReturnType.SpecialType == SpecialType.System_Void)
        {
            sb.AppendLine($"{indent}public async {asyncReturn} {proc.MethodName}Async({paramList})");
            sb.AppendLine($"{indent}{{");
            if (proc.Parameters.Length == 0)
            {
                sb.AppendLine($"{indent}    byte[] parameterData = global::System.Array.Empty<byte>();");
            }
            else
            {
                RpcBinaryCodec.EmitSerializeParameters(sb, indent + "    ", proc.Parameters);
            }

            sb.AppendLine($"{indent}    await RequestRPC({proc.MethodId}, parameterData, {proc.ReliableTypeExpression});");
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            sb.AppendLine($"{indent}public async {asyncReturn} {proc.MethodName}Async({paramList})");
            sb.AppendLine($"{indent}{{");
            if (proc.Parameters.Length == 0)
            {
                sb.AppendLine($"{indent}    byte[] parameterData = global::System.Array.Empty<byte>();");
            }
            else
            {
                RpcBinaryCodec.EmitSerializeParameters(sb, indent + "    ", proc.Parameters);
            }

            sb.AppendLine($"{indent}    byte[] resultBytes = await RequestRPC({proc.MethodId}, parameterData, {proc.ReliableTypeExpression});");
            sb.AppendLine($"{indent}    return {RpcMarshal.EmitDecodeReturnExpression(proc.ReturnType, "resultBytes")};");
            sb.AppendLine($"{indent}}}");
        }

        sb.AppendLine();
    }

    static void EmitIncomingProcedure(StringBuilder sb, MethodMetadata proc, string indent)
    {
        sb.AppendLine($"{indent}private byte[] {proc.MethodName}_Requested(byte[] parameterData)");
        sb.AppendLine($"{indent}{{");

        if (proc.Parameters.Length == 0)
        {
            if (proc.ReturnType.SpecialType == SpecialType.System_Void)
            {
                sb.AppendLine($"{indent}    {proc.MethodName}_Implementation();");
                sb.AppendLine($"{indent}    return global::System.Array.Empty<byte>();");
            }
            else
            {
                sb.AppendLine($"{indent}    {proc.ReturnType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)} result = {proc.MethodName}_Implementation();");
                sb.AppendLine($"{indent}    return {RpcMarshal.EmitEncodeReturnExpression(proc.ReturnType, "result")};");
            }
        }
        else
        {
            sb.AppendLine($"{indent}    using (var __rpcMs = new global::System.IO.MemoryStream(parameterData))");
            sb.AppendLine($"{indent}    using (var __rpcR = new global::System.IO.BinaryReader(__rpcMs))");
            sb.AppendLine($"{indent}    {{");
            RpcBinaryCodec.EmitDeserializeLocals(sb, indent + "        ", proc.Parameters, "__rpcR");
            string args = RpcBinaryCodec.BuildArgumentListFromLocals(proc.Parameters);
            if (proc.ReturnType.SpecialType == SpecialType.System_Void)
            {
                sb.AppendLine($"{indent}        {proc.MethodName}_Implementation({args});");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine($"{indent}    return global::System.Array.Empty<byte>();");
            }
            else
            {
                sb.AppendLine(
                    $"{indent}        {proc.ReturnType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)} result = {proc.MethodName}_Implementation({args});");
                sb.AppendLine($"{indent}        return {RpcMarshal.EmitEncodeReturnExpression(proc.ReturnType, "result")};");
                sb.AppendLine($"{indent}    }}");
            }
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        string partialKeyword = proc.ReturnType.SpecialType == SpecialType.System_Void ? "partial void" : $"partial {proc.ReturnType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}";
        sb.AppendLine($"{indent}private {partialKeyword} {proc.MethodName}_Implementation({ParameterDeclarationList(proc)});");
        sb.AppendLine();
    }

    static string ParameterDeclarationList(MethodMetadata proc)
    {
        return string.Join(", ", proc.Parameters.Select(p =>
            $"{p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)} {p.Name}"));
    }

    static void EmitDefaultMessageConverter(StringBuilder sb, string indent)
    {
        sb.AppendLine($"{indent}private sealed class DefaultMessageConverter : Communication.Shared.Messages.IMessageConverter");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    public byte[] Serialize(object message)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return MessageSerializer.Serialize(message);");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    public object Deserialize(global::System.ReadOnlySpan<byte> messageData)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return MessageSerializer.Deserialize(messageData.ToArray());");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    static void EmitStringHelpers(StringBuilder sb, string indent)
    {
        sb.AppendLine($"{indent}private static byte[] RpcEncodeString(string value)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    value ??= string.Empty;");
        sb.AppendLine($"{indent}    var bytes = global::System.Text.Encoding.UTF8.GetBytes(value);");
        sb.AppendLine($"{indent}    var buf = new byte[4 + bytes.Length];");
        sb.AppendLine($"{indent}    global::System.Buffer.BlockCopy(global::System.BitConverter.GetBytes(bytes.Length), 0, buf, 0, 4);");
        sb.AppendLine($"{indent}    global::System.Buffer.BlockCopy(bytes, 0, buf, 4, bytes.Length);");
        sb.AppendLine($"{indent}    return buf;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent}private static string RpcDecodeString(byte[] data)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if (data == null || data.Length < 4) return string.Empty;");
        sb.AppendLine($"{indent}    int len = global::System.BitConverter.ToInt32(data, 0);");
        sb.AppendLine($"{indent}    if (len <= 0 || 4 + len > data.Length) return string.Empty;");
        sb.AppendLine($"{indent}    return global::System.Text.Encoding.UTF8.GetString(data, 4, len);");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }
}

internal sealed class RpcHubEmitModel
{
    public string HubTypeName { get; set; } = "";
    public string? Namespace { get; set; }
    public bool IsServerEndpoint { get; set; }
    public MethodMetadata[] Outgoing { get; set; } = Array.Empty<MethodMetadata>();
    public MethodMetadata[] Incoming { get; set; } = Array.Empty<MethodMetadata>();
    public bool NeedsStringHelpers { get; set; }
}
